apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy}}
        resources:
          request:
            memory: {{ .Values.resources.memory }}
            cpu: {{ .Values.resources.cpu }}
          limits:
            memory: {{ .Values.resources.maxMemory }}
            cpu: {{ .Values.resources.maxCpu }}
