apiVersion: apps/v1
kind: Deployment
metadata:
  name: tyro-backend
  namespace: tyro-app
  labels:
    app: tyro-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tyro-backend
  template:
    metadata:
      labels:
        app: tyro-backend
    spec:
      serviceAccountName: admin
      containers:
      - name: tyro-backend
        imagePullPolicy: Always
        image: "gcr.io/{{ .Values.google-cloud.project-id }}/tyro-backend:1.0"
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: docker
          mountPath: /var/lib/docker
        - name: docker-socket
          mountPath: /var/run/docker.sock
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            cpu: 300m
            memory: 400Mi
        env:
        - name: POSTGRES_HOST
          value: tyro-db
        - name: POSTGRES_PASSWORD
          value: {{ .Values.database.password }}
        - name: GCP_PROJECT_ID
          value: {{ .Values.google-cloud.project-id }}
        - name: GCP_CREDENTIALS_ENCODED
          value: {{ .Values.google-cloud.credentials-encoded-base64 }}
        - name: GOOGLE_CLIENT_ID
          value: {{ .Values.google-cloud.api.client-id }}
        - name: GOOGLE_CLIENT_SECRET
          value: {{ .Values.google-cloud.api.client-secret }}
      volumes:
      - name: docker
        emptyDir: {}
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
