{{- define "randHex" -}}
    {{- $result := "" }}
    {{- range $i := until . }}
        {{- $rand_hex_char := mod (randNumeric 4 | atoi) 16 | printf "%x" }}
        {{- $result = print $result $rand_hex_char }}
    {{- end }}
    {{- $result }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: tyro-backend-token
type: Opaque
data:
  TOKEN: {{ randHex | b64enc }}
