apiVersion: v1
kind: Service
metadata:
  name: tyro-backend
  namespace: tyro-app
spec:
  type: LoadBalancer
  selector:
    app: tyro-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
