name: Build Component

inputs:
  repository:
    description: 'Repository to build'
    required: true
  dockerfile-path:
    description: 'Dockerfile to build'
    required: true
  image-name:
    description: 'Name of the image to build'
    required: true
  image-tag:
    description: 'Tag of the image to build'
    required: true

runs:
  using: "composite"
  steps:

  - name: Checkout
    uses: actions/checkout@v3
  
  - name: Checkout Backend
    uses: actions/checkout@v3
    with:
      repository: ${{ inputs.repository }}
      path: build-repo

  - name: Build docker image
    run: docker build -t gcr.io/$GOOGLE_PROJECT_ID/$IMAGE_NAME:$IMAGE_TAG build-repo/$DOCKERFILE_PATH
    env:
      GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
      DOCKERFILE_PATH: ${{ inputs.dockerfile-path }}
      IMAGE_NAME: ${{ inputs.image-name }}
      IMAGE_TAG: ${{ inputs.image-tag }}

  - name: Authenticate to GCP
    uses: google-github-actions/auth@v0
    with:
      credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

  - name: Set up Cloud SDK
    uses: google-github-actions/setup-gcloud@v0

  - name: Push to Google Container Registry
    run: |
      echo $GOOGLE_CREDENTIALS > credentials.json
      docker login -u _json_key --password-stdin https://gcr.io < credentials.json
      docker push gcr.io/$GOOGLE_PROJECT_ID/$IMAGE_NAME:$IMAGE_TAG
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
      IMAGE_NAME: ${{ inputs.image-name }}
      IMAGE_TAG: ${{ inputs.image-tag }}
