deployment:
  replicas: 1
  name:
  template:
    spec:
      serviceaccount: ""
      container:
        image:
          required: true
        port: 
          required: true
        resources:
          requests:
            memory: 300Mi
            cpu: 200m
          limits:
            memory: 300Mi
            cpu: 200m
  envs:
    required: false

service:
  name:
    required: true
  type: nil
    required: false
  ports:
    port:
      required: true
    target:
      required: true
    protocol: TCP
    node: nil
      required: false

      # api
      # target: 8000
      # port: 8000
      # node: 30001

      # db
      # target: 5432
      # port: 5432

account:
  service:
    name: admin

role:
  name: pods-list