apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: admin
      containers:
      - name: backend
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: mlflow-storage
          mountPath: /mnt/mlflow-storage
        - name: docker
          mountPath: /var/lib/docker
        - name: docker-socket
          mountPath: /var/run/docker.sock
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            cpu: 300m
            memory: 400Mi
        env:
        - name: POSTGRES_HOST
          value: database
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres_password }}
        - name: GCP_PROJECT_ID
          value: {{ .Values.gcp_project_id }}
        - name: GCP_CREDENTIALS
          value: {{ .Values.gcp_credentials | squote }}
      volumes:
      - name: mlflow-storage
        persistentVolumeClaim:
          claimName: mlflow-storage
      - name: docker
        emptyDir: {}
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
