apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: app
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        imagePullPolicy: Never
        image: mlflow:latest
        ports:
        - containerPort: 5000
      #   volumeMounts:
      #     - name: mlflow-storage
      #       mountPath: /mnt/mlflow-storage
      # volumes:
      # - name: mlflow-storage
      #   persistentVolumeClaim:
      #     claimName: mlflow-storage
