apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-storage
  namespace: app
spec:
  storageClassName: mlflow-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi