apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: app
spec:
  type: LoadBalancer
  selector:
    app: mlflow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
