apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mlflow-storage
  namespace: app
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none