apiVersion: apps/v1
kind: Deployment
metadata:
  name: tyro-ui
  namespace: tyro-app
  labels:
    app: tyro-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tyro-ui
  template:
    metadata:
      labels:
        app: tyro-ui
    spec:
      containers:
      - name: tyro-ui
        imagePullPolicy: Always
        image: "gcr.io/{{ .Values.google-cloud.project-id }}/tyro-ui:1.0"
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            cpu: 300m
            memory: 400Mi
