apiVersion: v1
kind: Service
metadata:
  name: tyro-ui
  namespace: tyro-app
spec:
  type: LoadBalancer
  selector:
    app: tyro-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
