apiVersion: apps/v1
kind: Deployment
metadata:
  name: tyro-mlflow
  namespace: tyro-app
  labels:
    app: tyro-mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tyro-mlflow
  template:
    metadata:
      labels:
        app: tyro-mlflow
    spec:
      containers:
      - name: tyro-mlflow
        imagePullPolicy: Always
        image: "gcr.io/{{ .Values.googleCloud.projectId }}/tyro-mlflow:1.0"
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: mlflow-storage
            mountPath: /mnt/mlflow-storage
      volumes:
      - name: mlflow-storage
        persistentVolumeClaim:
          claimName: tyro-mlflow-storage
