apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tyro-mlflow-storage
  namespace: tyro-app
spec:
  storageClassName: tyro-mlflow-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
