apiVersion: v1
kind: Service
metadata:
  name: tyro-mlflow
  namespace: tyro-app
spec:
  type: LoadBalancer
  selector:
    app: tyro-mlflow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
