apiVersion: apps/v1
kind: Deployment
metadata:
  name: tyro-db
  namespace: tyro-app
  labels:
    app: tyro-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tyro-db
  template:
    metadata:
      labels:
        app: tyro-db
    spec:
      containers:
      - name: tyro-db
        image: postgres:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            cpu: 300m
            memory: 400Mi
        env:
        - name: POSTGRES_USER
          value: {{ .Values.database.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.database.password }}
        - name: POSTGRES_DB
          value: {{ .Values.database.database }}
