apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.api.name }}
spec:
  selector:
    app:  {{ .Values.db.name }}
  ports:
    - protocol: {{ .Values.db.service.ports.protocol }}
      port: {{ .Values.db.service.ports.port }}
      targetPort: {{ .Values.db.service.ports.target }}