name: Deploy Image

on:
  workflow_call:
    inputs:
      stage:
        type: string
        required: true
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Get cluster credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: main-cluster
        location: ${{ secrets.GOOGLE_ZONE }}
        project_id: ${{ secrets.GOOGLE_PROJECT_ID }}

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Deploy
      run: |
        stage=${{ inputs.stage }}

        if [ $stage = "backend" ]; then
          helm upgrade --install backend ./kubernetes/backend --atomic \
            --set image=gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/backend \
            --set postgres_password=${{ secrets.POSTGRES_PASSWORD }} \
            --set gcp_project_id=${{ secrets.GOOGLE_PROJECT_ID }}

        elif [ $stage = "database" ]; then
          helm upgrade --install database ./kubernetes/database --atomic \
            --set postgres_user=${{ secrets.POSTGRES_USER }} \
            --set postgres_password=${{ secrets.POSTGRES_PASSWORD }} \
            --set postgres_db=${{ secrets.POSTGRES_DB }}

        elif [ $stage = "mlflow" ]; then
          helm upgrade --install mlflow ./kubernetes/mlflow --atomic
          
        fi
