name: Deploy Image

on:
  workflow_call:
  workflow_dispatch: # testing purposes
    

jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Test SDK
      run: |
        gcloud --quiet auth configure-docker
        gcloud info
