name: Deploy Image

on:
  workflow_call:
    inputs:
      stage:
        type: string
        required: true
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Get cluster credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: main-cluster
        location: ${{ secrets.GOOGLE_ZONE }}
        project_id: ${{ secrets.GOOGLE_PROJECT_ID }}


    - name: Configure Docker to use GCR
      run: gcloud auth configure-docker 

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        ls -la 

    - name: Deploy
      run: |
        docker pull gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}
        helm upgrade --install chart --atomic -f k8s/values-${{ inputs.stage }}.yaml k8s



    