name: Deploy a Helm chart to GCP

on:
  workflow_call:
    inputs:
      repository:
        type : string
        required: true
      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout to repo
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
    
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
    
    - name: Configure Docker to use GCR
      run: gcloud auth configure-docker -q gcr.io
