name: Deploy a Helm chart to GCP

on:
  workflow_call:
    inputs:
      repository:
        type: string
        required: true
      

jobs:
  deploy:
    runs-on: ubuntu-latest
    - name: Checkout to repo
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}


    - name: Authenticate to GCP
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Install Helm
      uses: Azure/setup-helm@v1

    - name: Deploy chart
      run:
        helm upgrade --install k8s
