name: Create Namespaces

on:
  workflow_call:

jobs:

  create-namespaces:
    name: Create Namespaces
    runs-on: ubuntu-latest
    steps:

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Get cluster credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: main-cluster
        location: ${{ secrets.GOOGLE_ZONE }}
        project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
      
    - name: Create namespaces
      shell: bash
      run: |
        kubectl create namespace istio-system --dry-run=client -o yaml | kubectl apply -f -
        kubectl create namespace tyro-models --dry-run=client -o yaml | kubectl apply -f -
        kubectl create namespace tyro-app --dry-run=client -o yaml | kubectl apply -f -
