name: Provisioning

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: Mode
        required: true
        default: Destroy
        options:
          - Destroy
          - Create
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: read

jobs:

  terraform-apply:
    if: github.event.inputs.mode == 'Create'
    name: 'Terraform: Create'
    uses: ./.github/workflows/terraform.yaml
    with:
      mode: Create
    secrets: inherit

  terraform-destroy:
    if: github.event.inputs.mode == 'Destroy'
    name: 'Terraform: Create'
    uses: ./.github/workflows/terraform.yaml
    with:
      mode: Destroy
    secrets: inherit

  create-namespaces:
    needs: [terraform-apply]
    name: Create Namespaces
    uses: ./.github/workflows/namespaces.yaml
    secrets: inherit

  install-istio:
    needs: [create-namespaces]
    uses: ./.github/workflows/install_istio.yaml
    secrets: inherit

  build-backend:
    needs: [terraform-apply]
    name: Build backend
    uses: ./.github/workflows/build.yaml
    with:
      repository: TyroML/backend
      dockerfile-path: app
      image-name: tyro-backend
      image-tag: '1.0'
    secrets: inherit

  build-frontend:
    needs: [terraform-apply]
    name: Build frontend
    uses: ./.github/workflows/build.yaml
    with:
      repository: TyroML/frontend
      dockerfile-path: .
      image-name: tyro-ui
      image-tag: '1.0'
    secrets: inherit

  build-mlflow:
    needs: [terraform-apply]
    name: Build mlflow
    uses: ./.github/workflows/build.yaml
    with:
      repository: TyroML/devops
      dockerfile-path: mlflow
      image-name: tyro-mlflow
      image-tag: '1.0'
    secrets: inherit

  deploy:
    name: Deploy
    needs: [install-istio, build-backend, build-frontend, build-mlflow]
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
