name: 'Destroy GCP Environment'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  terraform:
    name: 'Destroy resources'
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        TF_VAR_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        TF_VAR_DEFAULT_REGION: ${{ secrets.GOOGLE_REGION }}
        TF_VAR_DEFAULT_ZONE: ${{ secrets.GOOGLE_ZONE }}

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        TF_VAR_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        TF_VAR_DEFAULT_REGION: ${{ secrets.GOOGLE_REGION }}
        TF_VAR_DEFAULT_ZONE: ${{ secrets.GOOGLE_ZONE }}
