name: 'GCP Environment'

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: Mode
        required: true
        default: Create
        options:
          - Create
          - Destroy

permissions:
  contents: read

jobs:

  terraform:
    name: 'Deploy resources'
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        cd infrastructure
        terraform init
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        TF_VAR_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        TF_VAR_DEFAULT_REGION: ${{ secrets.GOOGLE_REGION }}
        TF_VAR_DEFAULT_ZONE: ${{ secrets.GOOGLE_ZONE }}

    - name: Terraform Plan
      run: |
        cd infrastructure
        terraform plan
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        TF_VAR_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        TF_VAR_DEFAULT_REGION: ${{ secrets.GOOGLE_REGION }}
        TF_VAR_DEFAULT_ZONE: ${{ secrets.GOOGLE_ZONE }}

    - name: Terraform Apply
      if: github.event.inputs.mode == 'Create'
      run: |
        cd infrastructure
        terraform apply -auto-approve
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        TF_VAR_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        TF_VAR_DEFAULT_REGION: ${{ secrets.GOOGLE_REGION }}
        TF_VAR_DEFAULT_ZONE: ${{ secrets.GOOGLE_ZONE }}

    - name: Terraform Destroy
      if: github.event.inputs.mode == 'Destroy'
      run: |
        cd infrastructure
        terraform destroy -auto-approve
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        TF_VAR_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        TF_VAR_DEFAULT_REGION: ${{ secrets.GOOGLE_REGION }}
        TF_VAR_DEFAULT_ZONE: ${{ secrets.GOOGLE_ZONE }}
